<!DOCTYPE html>
<html lang="en"><head>
<script src="ba_final_files/libs/clipboard/clipboard.min.js"></script>
<script src="ba_final_files/libs/quarto-html/tabby.min.js"></script>
<script src="ba_final_files/libs/quarto-html/popper.min.js"></script>
<script src="ba_final_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ba_final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ba_final_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ba_final_files/libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.31">

  <meta name="author" content="Lukas Buchmann">
  <meta name="dcterms.date" content="2026-07-01">
  <title>An Interactive Planning Tool for Wild Boar Connectivity and African Swine Fever Prevention</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="ba_final_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="ba_final_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="ba_final_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="custom.scss">
  <link href="ba_final_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="ba_final_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="ba_final_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="ba_final_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">An Interactive Planning Tool for Wild Boar Connectivity and African Swine Fever Prevention</h1>
  <p class="subtitle">Bachelor Thesis · Applied Digital Life Science · ZHAW</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Lukas Buchmann 
</div>
</div>
</div>

  <p class="date">2026-07-01</p>
</section>
<section id="the-problem" class="slide level2">
<h2>The problem</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="r-stack">
<div class="fragment fade-out" data-fragment-index="1">
<p><strong>African Swine Fever</strong></p>
<ul>
<li>Case fatality: 90–95 % · no vaccine</li>
<li>Stable in carcasses for months</li>
<li>Advancing ~1–3 km/month across Europe</li>
<li>Wild boar = primary reservoir</li>
</ul>
</div>
<div class="fragment fade-in" data-fragment-index="1">
<p><strong>The dilemma (Hess 1994)</strong></p>
<blockquote>
<p>Wildlife corridors can <em>increase</em> disease spread under ASF-like conditions</p>
</blockquote>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><img data-src="images/connectivity.png"></p>
</div></div>
<aside class="notes">
<p>Let me start with the core tension that motivated this thesis. African Swine Fever is one of the most dangerous livestock and wildlife diseases currently active in Europe. There is no vaccine, case fatality in wild boar approaches 100 percent, and the virus persists in carcasses for months. Since its introduction to the Caucasus in 2007, it has been moving westward steadily through wild boar populations.</p>
<p>What makes this particularly difficult from a management perspective is a fundamental dilemma that Hess identified in 1994. Under conditions of high virulence and direct-contact transmission — which match ASF almost perfectly — wildlife corridors can increase disease-driven population extinction risk rather than reduce it. The very forest connections that landscape ecologists work to protect can become pathways for a disease wave front.</p>
<p>So the question is not just “where are the corridors?” but “what happens to disease spread if we modify a specific one?”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-is-missing" class="slide level2">
<h2>What is missing</h2>
<p>Existing Swiss connectivity models — Fischer (2024), Urbina (2023) — are <strong>static</strong>.</p>
<p>They answer: <em>where are the corridors?</em></p>
<p>They cannot answer:</p>
<ul>
<li><em>Which zones need surveillance if ASF is detected here today?</em></li>
<li><em>What changes if we fence this road section?</em></li>
<li><em>Does a new overpass help or redirect the problem?</em></li>
</ul>
<aside class="notes">
<p>The gap is between excellent scientific products and operational management decisions. Fischer and Urbina produced rigorous static resistance surfaces and connectivity maps. But a veterinary officer who gets a confirmed ASF detection at six in the morning does not have time to rerun an R script. They need to pick a point on a map and immediately see which zones are at risk and whether a structural intervention would help.</p>
<p>That is the gap I set out to close.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="research-objectives" class="slide level2">
<h2>Research objectives</h2>
<p><strong>1 — Species-specific resistance surface</strong></p>
<p>Adapt the connectivity modelling framework from red deer to wild boar using GPS telemetry from Canton Aargau</p>
<p><strong>2 — Interactive QGIS planning tool</strong></p>
<p>Build a plugin that lets wildlife managers simulate ASF spread and test interventions — without programming</p>
<aside class="notes">
<p>The thesis has two deliverables. First, a resistance surface calibrated specifically for wild boar, since the Fischer and Urbina models were built for red deer. Wild boar have different movement patterns, different infrastructure avoidance responses, and a much higher tolerance for agricultural land. The model needed to be rebuilt from scratch for this species.</p>
<p>Second, an interactive QGIS plugin — the Wildboar Connectivity ASF tool — that takes that resistance surface and lets any user run five different connectivity and risk analyses from a single interface in under three minutes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="study-area" class="slide level2">
<h2>Study area</h2>
<div class="columns">
<div class="column" style="width:55%;">
<ul>
<li><strong>Calibration:</strong> Canton Aargau — GPS telemetry available</li>
<li><strong>Transfer:</strong> Canton Zürich — independent application area</li>
<li>25 m resolution · Swiss LV95</li>
<li>Landscape: Swiss Mittelland — motorways, rail, agriculture interrupting forested ridges</li>
</ul>
</div><div class="column" style="width:45%;">
<p><img data-src="../images/aargau_study_area.png"></p>
</div></div>
<aside class="notes">
<p>Geographically the study sits in the Swiss Mittelland. Canton Aargau is where the GPS data was collected, so that is where the model is calibrated. Canton Zürich is then the independent transfer target — I applied the Aargau model to Zürich without any Zürich-specific telemetry, which tests whether the coefficients generalise.</p>
<p>The landscape is typical for this region: a relatively flat plateau cut by the A1 motorway and several major rail lines, with forested ridges running roughly east-west that are the main wildlife corridors.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="from-gps-tracks-to-resistance-surface" class="slide level2">
<h2>From GPS tracks to resistance surface</h2>
<pre><code>GPS telemetry (Aargau, 2014–2017, 15 min interval)
        │
        ▼
Preprocessing  ──  exclude short deployments, drop steps &gt; 3,000 m
        │
        ▼
Step classification  ──  in-matrix (7,824) · in-patch (125,285)
        │
        ▼
iSSF fitting  ──  7 covariates · 10 random steps each
        │
        ▼
Resistance surface  ──  R = exp(4 · (1 − S))
        │
        ▼
Transfer to Zürich  ──  same β · Zürich-local normalisation</code></pre>
<aside class="notes">
<p>The pipeline starts with raw GPS data from 16 wild boar collared in Aargau between 2014 and 2017 at a 15-minute fix interval. After preprocessing — removing short deployments, dropping biologically implausible steps above 3000 metres — I classified each step as either in-matrix or in-patch using a three-rule hierarchical classifier. Only the in-matrix transit steps go into the iSSF, because those are the steps where selection of movement corridors actually happens. The iSSF produces beta coefficients that quantify which habitats animals prefer or avoid during transit. Those coefficients feed into the resistance surface through the Keeley exponential transformation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="step-classification" class="slide level2">
<h2>Step classification</h2>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 35%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Rule</th>
<th>Criterion</th>
<th style="text-align: right;">Steps</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Length &gt; 250 m</td>
<td style="text-align: right;">4,759</td>
<td style="text-align: right;">60.8 %</td>
</tr>
<tr class="even">
<td>2</td>
<td>Length &gt; 150 m <strong>and</strong> |angle| &lt; π/4</td>
<td style="text-align: right;">2,748</td>
<td style="text-align: right;">35.1 %</td>
</tr>
<tr class="odd">
<td>3</td>
<td>≥ 3 consecutive: length &gt; 100 m <strong>and</strong> |angle| &lt; π/4</td>
<td style="text-align: right;">317</td>
<td style="text-align: right;">4.1 %</td>
</tr>
<tr class="even">
<td>—</td>
<td>Remaining (in-patch default)</td>
<td style="text-align: right;">125,285</td>
<td style="text-align: right;">—</td>
</tr>
</tbody>
</table>
<p><strong>Result: 7,824 in-matrix steps (5.9 %) · 14 individuals</strong></p>
<aside class="notes">
<p>The classifier works hierarchically. Rule 1 catches long, clearly directional steps above 250 metres. Rule 2 catches medium-distance steps that are also directionally consistent — turning angle below π/4. Rule 3 catches sustained runs where no individual step is particularly long, but the animal maintains direction over at least three consecutive steps. Anything that fails all three rules is conservatively labelled in-patch.</p>
<p>The thresholds are my own methodological decisions informed by published wild boar movement data — Podgórski’s speed data, Clontz’s HMM results on the traveling state, and Benhamou’s conceptual framework for in-patch versus in-matrix movement. None of those papers state these exact values as ready-to-use rules.</p>
<p>The result is that 94 percent of steps are in-patch, which makes biological sense. Wild boar spend most of their time foraging and resting in a patch. The 6 percent that are in-matrix are the transit events the model is built on.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="issf-7-covariates-retained" class="slide level2">
<h2>iSSF — 7 covariates retained</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>14 candidates → <strong>7 retained</strong> (all VIF &lt; 1.5)</p>
<p><strong>Kept:</strong> forest density 50 m, forest density 1000 m, distance to water, distance to main roads, secondary roads, railways, settlements</p>
<p><strong>Excluded:</strong> slope, TRI, edge distance, forest binary, fenced road distance, flowing / lake distance separately</p>
</div><div class="column" style="width:50%;">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Fenced road exclusion</strong></p>
<p>Initial β = −0.60 → apparent attraction to motorways.</p>
<p>Cause: animals <em>pacing along</em> fenced motorways, not crossing them. This is a data artefact, not true preference. Fenced roads belong in the burn-in, not the regression.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>I started with 14 candidate covariates from the swissTLM3D dataset and the DHM25 elevation model. After a VIF check to flag collinearity, seven survived with all VIFs below 1.5.</p>
<p>The most interesting exclusion is distance to fenced roads. In the initial exploratory model, the coefficient came back negative — apparently indicating that wild boar are attracted to motorways. That is ecologically implausible. What is actually happening is that an animal that cannot cross a fenced motorway walks along the fence for an extended distance, creating a systematic spatial association between the animal and the motorway in the data. The iSSF picks this up as apparent attraction. The correct treatment is to place fenced roads in the burn-in as absolute barriers and leave them out of the regression.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="issf-results" class="slide level2">
<h2>iSSF results</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p><img data-src="../images/issf_coefficients.png"></p>
</div><div class="column" style="width:45%;">
<ul>
<li>All 7 coefficients <strong>positive</strong></li>
<li>Positive = preferred during transit = higher resistance</li>
<li>Forest density 50 m: tightest CI — most reliably estimated</li>
<li>Railway: strong avoidance, wide CI (sparse in Aargau)</li>
<li>Movement kernel terms both highly significant</li>
</ul>
</div></div>
<aside class="notes">
<p>All seven retained coefficients are positive. A positive coefficient means that as the value of that variable increases, selection during transit increases — or put differently, animals prefer to move through areas with high forest density, far from infrastructure, and near water.</p>
<p>The forest density at the 50 metre scale has the smallest standard error. That is the most reliably estimated effect: immediate cover is the dominant driver of where a wild boar chooses to transit through the landscape.</p>
<p>Railway avoidance has the strongest point estimate but the widest confidence interval, because Aargau has relatively few railway lines and the training data for that covariate is sparse. The avoidance is real, but we should not over-interpret the precise magnitude.</p>
<p>The two movement kernel terms — log of step length and cosine of turning angle — are both strongly significant, which confirms that it is necessary to control for the movement process itself when estimating habitat selection.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="resistance-surface-aargau" class="slide level2">
<h2>Resistance surface — Aargau</h2>

<img data-src="../images/suitability_resistance_maps_Aargau.png" style="width:100.0%" class="r-stretch"><div style="font-size:0.75em; color:#555">
<p>Median resistance: 35.1 · theoretical midpoint: 27.8 · range: 1–54.6 · NoData = absolute barriers</p>
</div>
<aside class="notes">
<p>The resistance surface reproduces the expected landscape structure. Forested ridges appear as low-resistance green corridors. The agricultural plain and urban areas push resistance up toward the maximum. Motorways and large lakes appear as grey NoData — absolute barriers.</p>
<p>The median resistance being above the scale midpoint tells us that more than half the landscape is costly terrain for a transiting wild boar. This is consistent with what ecologists call a landscape of fear — animals are reluctant to cross open ground and concentrate their transit into a small fraction of the landscape.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="transfer-to-zürich" class="slide level2">
<h2>Transfer to Zürich</h2>

<img data-src="../images/suitability_resistance_maps_Zurich.png" style="width:100.0%" class="r-stretch"><div style="font-size:0.75em; color:#555">
<p>Aargau β and z-standardisation reused · Zürich-specific normalisation for within-canton contrast · permanent ASF fences burned in as absolute barriers</p>
</div>
<aside class="notes">
<p>For the transfer to Zürich, I reused the Aargau beta coefficients and z-standardisation parameters unchanged. This keeps the coefficients interpretable — a unit change in a covariate still means a unit change on the Aargau scale. Only the final min-max normalisation of the linear predictor is computed on the Zürich-specific range, so that the full resistance scale is used within Zürich rather than being compressed.</p>
<p>One additional element unique to Zürich is the permanent ASF prevention fence network from the cantonal veterinary authority. Those are burned in as absolute barriers alongside fenced motorways and large lakes. Wildlife passages override everything.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="qgis-plugin-workflow" class="slide level2">
<h2>QGIS Plugin — workflow</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ol type="1">
<li>Load resistance raster</li>
<li>(Optional) upload habitat shapefile</li>
<li>Draw fences or overpasses on the map</li>
<li>Click outbreak origin</li>
<li>Select analyses · press Run</li>
<li>Styled layers appear in ~3 minutes</li>
</ol>
<p><strong>No programming required</strong></p>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Module</th>
<th>Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LCP corridors</td>
<td>Dijkstra traceback</td>
</tr>
<tr class="even">
<td>Infection risk</td>
<td>Cost-distance kernel</td>
</tr>
<tr class="odd">
<td>Circuitscape</td>
<td>Random walk current</td>
</tr>
<tr class="even">
<td>BCRW</td>
<td>Von Mises biased walk</td>
</tr>
<tr class="odd">
<td>IBMM</td>
<td>iSSF-based agents</td>
</tr>
</tbody>
</table>
</div></div>
<aside class="notes">
<p>The plugin is designed so that anyone who can open QGIS and load a raster can use it. After loading the resistance surface, the user picks an outbreak point on the map with a single click. They can optionally draw fence segments or place new wildlife overpasses — those modifications are applied to a copy of the raster in memory, so the original file is never touched. Then they select which of the five analyses to run and press Run.</p>
<p>Everything happens in a background thread so QGIS stays responsive. All outputs appear as styled map layers within about three minutes for a typical 10-kilometre analysis window.</p>
<p>The five modules are complementary: LCP gives the backbone corridor, infection risk maps the EFSA zones, Circuitscape identifies bottlenecks, BCRW provides a stochastic cross-check, and the IBMM adds an epidemiological layer calibrated to the ASF infectious period.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="demo-baseline-winterthur" class="slide level2">
<h2>Demo — Baseline (Winterthur)</h2>

<img data-src="../images/baseline.png" style="width:100.0%" class="r-stretch"><aside class="notes">
<p>This is the baseline scenario with the outbreak origin placed north of Winterthur city centre. LCP corridors trace the main forest ridges running north-east and north-west. The infection risk surface shows the high-risk zone extending roughly 2.5 to 3.5 kilometres in the direction of continuous forest, compressed toward Winterthur where urban resistance is high. The EFSA surveillance zone boundary — risk threshold 0.15 — reaches about 8 to 10 kilometres through the forested corridors.</p>
<p>All five analyses completed in under 3 minutes. The Circuitscape pinchpoint map identifies two main bottlenecks where connectivity is strongly funnelled — those are the priority locations for any fence intervention.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="demo-scenario-comparison-virtual-fence-overpass" class="slide level2">
<h2>Demo — Scenario comparison (virtual fence + overpass)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../images/lcp_winti.png"></p>
<figcaption>Baseline</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../images/lcp_withfence.png"></p>
<figcaption>After intervention</figcaption>
</figure>
</div>
</div></div>
<div style="font-size:0.8em; color:#444; margin-top:0.3em">
<p>Fence across principal pinchpoint · new overpass on northern corridor → LCP backbone reroutes, current density redistributes</p>
</div>
<aside class="notes">
<p>Starting from the baseline, I drew a fence segment across the main bottleneck identified by Circuitscape, and placed a new virtual overpass on the northern corridor. Left panel is baseline, right panel is after the intervention.</p>
<p>The primary corridor is blocked and the model routes through the overpass instead. The pinchpoint raster confirms that current density has redistributed away from the fenced segment toward secondary corridors and the new passage.</p>
<p>This scenario comparison happens in a single QGIS session. The user can switch between configurations without rerunning anything, which is exactly what the design aimed for.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="risk-and-contamination-fence-scenario" class="slide level2">
<h2>Risk and contamination — fence scenario</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="../images/risk_ibmm_fence.png"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="../images/with_fence.png"></p>
</div></div>
<aside class="notes">
<p>The infection risk surface and the IBMM contamination map tell related but different stories. The infection risk is deterministic — cost-distance contours from the outbreak point. The IBMM is stochastic: 2,000 simulated agents, each with a finite lifespan drawn from the ASF infectious period distribution.</p>
<p>The fence has a visible asymmetric effect. The risk zone shrinks on the fenced side and extends further through the new overpass. A wildlife manager looking at this immediately sees that the fence works, but that it redirects rather than eliminates connectivity — which is the ecologically correct expectation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="discussion" class="slide level2">
<h2>Discussion</h2>
<div class="columns" style="font-size:0.82em">
<div class="column" style="width:50%;">
<p><strong>What worked</strong></p>
<ul>
<li>Coefficients ecologically interpretable: forest cover, infrastructure avoidance</li>
<li>Resistance surface reproduces expected landscape structure</li>
<li>Five modules complement each other well</li>
<li>Interactivity closes the gap to operational management</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Key limitations</strong></p>
<ul>
<li>No Zürich telemetry → no quantitative validation</li>
<li>10-year gap between telemetry (2014–17) and landscape data (2026)</li>
<li>Keeley C = 4 from red deer, no wild-boar-specific value</li>
<li>IBMM can step across absolute barriers (endpoint selection artefact)</li>
</ul>
</div></div>
<aside class="notes">
<p>The iSSF results are ecologically coherent. All infrastructure classes produce avoidance during transit, forest density drives the most precisely estimated effect, and the resistance surface looks like what you would expect from field knowledge of the study area.</p>
<p>The biggest methodological caveat is the Keeley constant. C equals 4 controls how steeply resistance rises as suitability falls. That value was calibrated by Fischer for red deer. Wild boar are more generalist and may experience the landscape as less costly — a lower C might be more appropriate, but no species-specific value exists in the literature.</p>
<p>On the validation side: I have no Zürich telemetry to test the transferred surface against. Model quality is assessed through visual plausibility only. That is the most important thing to fix in future work.</p>
<p>The IBMM has a known artefact where agents can occasionally appear on the wrong side of an absolute barrier. This happens because endpoint selection checks habitat suitability at the destination but not whether the path crosses a NaN wall. It is rare, but worth flagging.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="conclusions-and-outlook" class="slide level2">
<h2>Conclusions and outlook</h2>
<div class="columns" style="font-size:0.82em">
<div class="column" style="width:55%;">
<p><strong>Deliverables</strong></p>
<ul>
<li>First wild-boar-specific resistance surface for the Swiss Mittelland</li>
<li>QGIS plugin: 5 analyses · &lt;3 min · no programming required</li>
<li>Addresses the Hess (1994) trade-off in an operational planning context</li>
</ul>
<p><strong>The tool is ready for pilot use</strong></p>
</div><div class="column" style="width:45%;">
<p><strong>Priority next steps</strong></p>
<ol type="1">
<li>GPS telemetry from Zürich wild boar — validation</li>
<li>Population density weighting</li>
<li>Day / night movement distinction</li>
<li>Better forest data (lidar / canopy height)</li>
<li>Cross-border data (German side of Rhine)</li>
</ol>
</div></div>
<aside class="notes">
<p>To summarise: this thesis produced two concrete deliverables. The resistance surface is the first one calibrated specifically for wild boar in the Swiss Mittelland. The QGIS plugin is, to my knowledge, the first interactive ASF scenario planning tool that integrates five complementary connectivity models in a single accessible interface.</p>
<p>The most important next step is straightforward: get GPS tracking data from wild boar in Zürich and run a formal validation. Everything else on the list is valuable, but none of it matters as much as knowing whether the model actually captures how Zürich wild boar move.</p>
<p>Thank you — I am happy to take questions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>BA Final Presentation | Lukas Buchmann | ZHAW</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="ba_final_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="ba_final_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="ba_final_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="ba_final_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="ba_final_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="ba_final_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="ba_final_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="ba_final_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="ba_final_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="ba_final_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>